-- Add comprehensive medical questions for all subject blocks

-- Anatomy - Lower Limb questions
INSERT INTO public.quiz_questions (category_id, subject_id, block_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
('basic-medical-sciences', 'anatomy', 'lower-limb', 'Which muscle is the strongest flexor of the hip joint?', 'Psoas major', 'Iliacus', 'Rectus femoris', 'Iliopsoas', 3, 'The iliopsoas (combination of psoas major and iliacus) is the strongest flexor of the hip joint.'),
('basic-medical-sciences', 'anatomy', 'lower-limb', 'The popliteal artery is a continuation of which artery?', 'Common iliac artery', 'Internal iliac artery', 'Femoral artery', 'External iliac artery', 2, 'The popliteal artery is the continuation of the femoral artery as it passes through the adductor hiatus.'),
('basic-medical-sciences', 'anatomy', 'lower-limb', 'Which nerve supplies the muscles of the anterior compartment of the leg?', 'Tibial nerve', 'Common peroneal nerve', 'Deep peroneal nerve', 'Superficial peroneal nerve', 2, 'The deep peroneal nerve supplies the muscles of the anterior compartment of the leg.'),
('basic-medical-sciences', 'anatomy', 'lower-limb', 'The great saphenous vein terminates into which vessel?', 'Inferior vena cava', 'Femoral vein', 'External iliac vein', 'Popliteal vein', 1, 'The great saphenous vein terminates into the femoral vein at the saphenofemoral junction.'),
('basic-medical-sciences', 'anatomy', 'lower-limb', 'Which ligament prevents posterior displacement of the tibia on the femur?', 'Anterior cruciate ligament', 'Posterior cruciate ligament', 'Medial collateral ligament', 'Lateral collateral ligament', 1, 'The posterior cruciate ligament prevents posterior displacement of the tibia on the femur.'),

-- Anatomy - Thorax questions
('basic-medical-sciences', 'anatomy', 'thorax', 'The right main bronchus is characterized by being:', 'Longer and more vertical', 'Shorter and more vertical', 'Longer and more horizontal', 'Shorter and more horizontal', 1, 'The right main bronchus is shorter, wider, and more vertical than the left, making it more likely for aspirated objects to enter.'),
('basic-medical-sciences', 'anatomy', 'thorax', 'Which structure forms the posterior boundary of the superior mediastinum?', 'Manubrium sterni', 'Body of sternum', 'T1-T4 vertebrae', 'T5-T8 vertebrae', 2, 'The bodies of T1-T4 vertebrae form the posterior boundary of the superior mediastinum.'),
('basic-medical-sciences', 'anatomy', 'thorax', 'The phrenic nerve originates from which spinal segments?', 'C2, C3, C4', 'C3, C4, C5', 'C4, C5, C6', 'C5, C6, C7', 1, 'The phrenic nerve arises from C3, C4, and C5 spinal segments (C3, 4, 5 keeps the diaphragm alive).'),
('basic-medical-sciences', 'anatomy', 'thorax', 'Which heart valve is most commonly affected in rheumatic fever?', 'Aortic valve', 'Mitral valve', 'Tricuspid valve', 'Pulmonary valve', 1, 'The mitral valve is most commonly affected in rheumatic heart disease.'),
('basic-medical-sciences', 'anatomy', 'thorax', 'The left recurrent laryngeal nerve loops around which structure?', 'Left subclavian artery', 'Arch of aorta', 'Left common carotid artery', 'Ligamentum arteriosum', 1, 'The left recurrent laryngeal nerve loops around the arch of aorta and ligamentum arteriosum.'),

-- Anatomy - Abdomen questions
('basic-medical-sciences', 'anatomy', 'abdomen', 'Which structure passes through the esophageal hiatus?', 'Esophagus only', 'Esophagus and vagus nerves', 'Esophagus and phrenic nerves', 'Esophagus, vagus nerves, and left gastric vessels', 3, 'The esophageal hiatus (T10) transmits the esophagus, vagus nerves, and left gastric vessels.'),
('basic-medical-sciences', 'anatomy', 'abdomen', 'The portal vein is formed by the union of which vessels?', 'Superior and inferior mesenteric veins', 'Splenic and superior mesenteric veins', 'Splenic and inferior mesenteric veins', 'Superior mesenteric and left gastric veins', 1, 'The portal vein is formed by the union of the splenic and superior mesenteric veins.'),
('basic-medical-sciences', 'anatomy', 'abdomen', 'Which part of the duodenum is retroperitoneal?', 'First part only', 'Second and third parts', 'All parts except first', 'All four parts', 2, 'The second, third, and fourth parts of the duodenum are retroperitoneal; only the first part is intraperitoneal.'),
('basic-medical-sciences', 'anatomy', 'abdomen', 'The appendix is typically located at which anatomical landmark?', 'Right iliac fossa', 'McBurney point', 'Umbilicus', 'Right lumbar region', 1, 'McBurney point (1/3 the distance from anterior superior iliac spine to umbilicus) marks the typical location of the appendix.'),
('basic-medical-sciences', 'anatomy', 'abdomen', 'Which kidney is normally positioned lower?', 'Right kidney', 'Left kidney', 'Both are at same level', 'Varies with gender', 0, 'The right kidney is typically positioned lower than the left due to the presence of the liver above it.'),

-- Physiology Block 1 questions
('basic-medical-sciences', 'physiology', 'block-1', 'The normal cardiac output in a healthy adult at rest is approximately:', '3-4 L/min', '5-6 L/min', '7-8 L/min', '9-10 L/min', 1, 'Normal cardiac output at rest is approximately 5-6 L/min (stroke volume × heart rate).'),
('basic-medical-sciences', 'physiology', 'block-1', 'Which phase of the cardiac cycle is longest?', 'Isovolumetric contraction', 'Ventricular ejection', 'Isovolumetric relaxation', 'Ventricular filling', 3, 'Ventricular filling (diastole) is the longest phase of the cardiac cycle, especially at rest.'),
('basic-medical-sciences', 'physiology', 'block-1', 'The primary pacemaker of the heart is located in:', 'AV node', 'SA node', 'Bundle of His', 'Purkinje fibers', 1, 'The sinoatrial (SA) node is the primary pacemaker, generating impulses at 60-100 bpm.'),
('basic-medical-sciences', 'physiology', 'block-1', 'Which factor has the greatest effect on stroke volume?', 'Heart rate', 'Preload', 'Afterload', 'Contractility', 1, 'Preload (venous return/ventricular filling) has the greatest effect on stroke volume via the Frank-Starling mechanism.'),
('basic-medical-sciences', 'physiology', 'block-1', 'The Frank-Starling mechanism describes the relationship between:', 'Heart rate and contractility', 'Venous return and stroke volume', 'Blood pressure and heart rate', 'Afterload and preload', 1, 'Frank-Starling mechanism: increased venous return → increased ventricular filling → increased stroke volume.'),

-- Physiology Block 2 questions
('basic-medical-sciences', 'physiology', 'block-2', 'The normal respiratory rate in adults is:', '8-12 breaths/min', '12-20 breaths/min', '20-25 breaths/min', '25-30 breaths/min', 1, 'Normal respiratory rate in healthy adults is 12-20 breaths per minute.'),
('basic-medical-sciences', 'physiology', 'block-2', 'Which gas law explains the relationship between pressure and volume in the lungs?', 'Dalton law', 'Henry law', 'Boyle law', 'Charles law', 2, 'Boyle law (P1V1 = P2V2) explains how pressure changes affect lung volume during breathing.'),
('basic-medical-sciences', 'physiology', 'block-2', 'The primary respiratory center is located in:', 'Pons', 'Medulla oblongata', 'Midbrain', 'Cerebellum', 1, 'The medulla oblongata contains the primary respiratory center controlling breathing rhythm.'),
('basic-medical-sciences', 'physiology', 'block-2', 'Which factor is the primary driver of respiration under normal conditions?', 'Oxygen levels', 'Carbon dioxide levels', 'pH levels', 'Blood pressure', 1, 'CO2 levels (and resulting pH changes) are the primary drivers of respiration under normal conditions.'),
('basic-medical-sciences', 'physiology', 'block-2', 'The oxygen-hemoglobin dissociation curve shifts to the right when:', 'pH increases', 'Temperature decreases', 'CO2 increases', 'Oxygen increases', 2, 'Increased CO2, decreased pH, increased temperature, and increased 2,3-DPG shift the curve right (Bohr effect).'),

-- Pathology Block 1 questions
('path-pharm', 'pathology', 'block-1', 'Which type of necrosis is characteristically seen in tuberculosis?', 'Coagulative necrosis', 'Liquefactive necrosis', 'Caseous necrosis', 'Fat necrosis', 2, 'Caseous necrosis (cheese-like) is characteristic of tuberculosis and other granulomatous infections.'),
('path-pharm', 'pathology', 'block-1', 'The most common type of lung cancer is:', 'Adenocarcinoma', 'Squamous cell carcinoma', 'Small cell carcinoma', 'Large cell carcinoma', 0, 'Adenocarcinoma is now the most common type of lung cancer, especially in non-smokers.'),
('path-pharm', 'pathology', 'block-1', 'Which marker is most specific for myocardial infarction?', 'CK-MB', 'Troponin I', 'AST', 'LDH', 1, 'Troponin I is the most specific and sensitive marker for myocardial infarction.'),
('path-pharm', 'pathology', 'block-1', 'Virchow triad includes all except:', 'Endothelial injury', 'Hypercoagulability', 'Venous stasis', 'Arterial hypertension', 3, 'Virchow triad includes endothelial injury, hypercoagulability, and venous stasis - not arterial hypertension.'),
('path-pharm', 'pathology', 'block-1', 'Which type of hypersensitivity reaction is anaphylaxis?', 'Type I', 'Type II', 'Type III', 'Type IV', 0, 'Anaphylaxis is a Type I (immediate) hypersensitivity reaction mediated by IgE.'),

-- Pharmacology Block 1 questions
('path-pharm', 'pharmacology', 'block-1', 'Which drug is a selective beta-1 blocker?', 'Propranolol', 'Metoprolol', 'Timolol', 'Nadolol', 1, 'Metoprolol is a cardioselective (beta-1 selective) blocker, unlike propranolol which blocks both beta-1 and beta-2.'),
('path-pharm', 'pharmacology', 'block-1', 'The mechanism of action of aspirin involves:', 'Reversible COX inhibition', 'Irreversible COX inhibition', 'Lipoxygenase inhibition', 'Phospholipase A2 inhibition', 1, 'Aspirin irreversibly inhibits cyclooxygenase (COX) enzymes by acetylating serine residues.'),
('path-pharm', 'pharmacology', 'block-1', 'Which antiarrhythmic drug can cause pulmonary toxicity?', 'Lidocaine', 'Quinidine', 'Amiodarone', 'Verapamil', 2, 'Amiodarone can cause serious pulmonary toxicity including pulmonary fibrosis with chronic use.'),
('path-pharm', 'pharmacology', 'block-1', 'ACE inhibitors work by blocking the conversion of:', 'Angiotensin I to Angiotensin II', 'Angiotensinogen to Angiotensin I', 'Angiotensin II to Angiotensin III', 'Renin to Angiotensinogen', 0, 'ACE inhibitors block the conversion of Angiotensin I to Angiotensin II, reducing vasoconstriction.'),
('path-pharm', 'pharmacology', 'block-1', 'Which diuretic is potassium-sparing?', 'Furosemide', 'Hydrochlorothiazide', 'Spironolactone', 'Mannitol', 2, 'Spironolactone is a potassium-sparing diuretic that works by blocking aldosterone receptors.');