// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzhmejlynzkgyrpuzcnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6aG1lamx5bnprZ3lycHV6Y25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzA1NTQsImV4cCI6MjA2NzQwNjU1NH0.dlsO08_C40q6_CBjEF276n6q8l7WuC1OLVtl096NDMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});